#!/usr/bin/env groovy

def gv

pipeline {
    agent any
    tools {
        nodejs 'node'
    }
    stages {

        stage("init") {
            steps {
                script {
                    gv = load "infra/jenkins/script.groovy"
                }
            }
        }
        stage("Run") {
            steps {
                script {
                    gv.runTest()
                }
            }
        }
    }
    post {
        success {
            // Notify GitHub on success
            githubNotify(
                status: 'SUCCESS',
                description: 'Build successful',
                context: 'Jenkins'
            )
        }
        failure {
            // Notify GitHub on failure
            githubNotify(
                status: 'FAILURE',
                description: 'Build failed',
                context: 'Jenkins'
            )
        }
    }   
}
